# Generated by Django 5.0.6 on 2024-06-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'author___',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category___',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('authors', models.ManyToManyField(related_name='books', to='books.author')),
                ('categories', models.ManyToManyField(related_name='books', to='books.category')),
            ],
            options={
                'db_table': 'book___',
            },
        ),
    ]
